[package]
name = "day7"
version = "0.1.0"
authors = ["SavageMessiah <cardboard42@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.42"
pest = "2.1.3"
pest_derive = "2.1.0"
